name: PermIconomy
main: com.Cutch.bukkit.PermIconomy.PermIconomy
version: 1.0
author: Cutch
commands:
  permi:
    description: The Bridge between Permissions and IConomy
    usage: /permi [buy|list|auth|authlist|reload]