name: PermIconomy
main: com.Cutch.bukkit.PermIconomy.PermIconomy
version: 1.02
author: Cutch
commands:
  permi:
    description: The Bridge between Permissions and IConomy
    usage: /permi [buy|auto|list|rentals|auth|authlist|reload]